# Generated by Django 3.2.6 on 2021-08-18 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, default='do it'),
        ),
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2021-08-18'),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2021-08-18'),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default=datetime.datetime(2021, 8, 18, 15, 19, 4, 707802, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
